import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style dangerouslySetInnerHTML={{
          __html: `
            /* Next.js開発用UI のみ非表示（設定ボタンは除外） */
            div[id*="__next-build"], div[class*="__nextjs"], div[data-nextjs-toast] { display: none !important; }
            nextjs-portal, #__next-build-watcher { display: none !important; }
            /* ビルドインジケーターのみ非表示 */
            div[style*="pointer-events: none"] { display: none !important; }
          `
        }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
